@startuml



title 中台通用-各系统交互时序

participant 业务系统 #EEEBDC
participant 业务风控系统 #EEEBDC
participant 产品配置中心
participant 统一进件
participant Artemis
participant 风控引擎
participant 额度
'participant 天玑
participant 资金
'actor 财务



== 用信流程 ==

业务系统 -> 统一进件: 放款进件数据保存
业务系统 -> 统一进件: 进件提交
统一进件 -\ Artemis: 风控审核 /api/v1/artemis/approval/audit-risk-flow
activate Artemis
Artemis -> Artemis: 风控路由
统一进件 <- Artemis: 快照接口 /api/1.0/loan-app-snapshot
Artemis -> 风控引擎: 放款风控申请
Artemis -> 额度: 获得利率
note left
仅针对风险定价产品
end note
统一进件 <- Artemis: 放款风控结果/风险定价利率 loanAppInfo.loanRate
deactivate Artemis
业务系统 <-- 统一进件: 放款风控结果（MQ）

|||

group 用信人工风控，取决于产品
    业务系统 -> 统一进件: 用信进件补充数据保存
    业务系统 -\ 统一进件: 进件提交（人工风控）
    统一进件 -\ Artemis: 风控审核 /api/v1/artemis/approval/audit-risk-flow
    activate Artemis
    Artemis -> Artemis: 风控路由
    业务风控系统 /- Artemis: 路由至业务风控系统
    activate 业务风控系统
    |||
    业务风控系统 -\ Artemis: 用信风控人工审核结果通知 /api/v1/artemis/approval/manual-risk-audit
    deactivate 业务风控系统
    统一进件 /- Artemis: 放款风控结果
    deactivate Artemis
    业务系统 /-- 统一进件: 放款风控结果（MQ）
end


业务系统 -\ Artemis: 4.1.1.1 创建资金订单接口v1
activate Artemis
统一进件 <- Artemis: 快照接口 /api/1.0/loan-app-snapshot
统一进件 <- Artemis: 使用uusUnionId更新withholdingUserCode
Artemis -> 额度: 额度查询
统一进件 <- Artemis: 更新额度platformAdvisiedCreditLimit
Artemis -\ 资金: T1.1.1_资金路由申请
Artemis /-- 资金: T1.1.3_资金路由申请结果通知
统一进件 <- Artemis: 更新资金路由结果fundChannel、mainChannel
note right
E.g. channelCode=ZJF116, mainChannelCode=149, mainChannelName=博能小额贷款有限公司
end note
统一进件 <- Artemis: 设置financeId /api/1.0/loan-app/finance-id/{loanAppCode}
产品配置中心 <- 统一进件: 获取financeId
业务系统 <-- Artemis: 资金路由结果（MQ）
deactivate Artemis

业务系统 -> Artemis: 4.1.1.2 取消路由接口
activate Artemis
Artemis <-> 资金: T5.1.1_订单撤销
note left
由于存在风控前置的情况，业务可能在风控拒绝时取消该进件
故仅在资金已调用过路由情况下，取消资金订单
end note
Artemis <-> 统一进件: 取消进件申请 /api/1.0/loan-app
deactivate Artemis

业务系统 -> Artemis: 4.3.1 查询资金订单v1
activate Artemis
note right
Artemis根据流程状态需要，实时查询路由或放款结果
end note
Artemis <-> 资金: T1.1.2_资金路由申请结果查询
统一进件 <- Artemis: 更新资金路由结果fundChannel、mainChannel
note right
当首次有路由结果时，会更新统一进件并更新financeId
end note
统一进件 <- Artemis: 设置financeId /api/1.0/loan-app/finance-id/{loanAppCode}
产品配置中心 <- 统一进件: 获取financeId
Artemis<-> 天玑: /api/1.0/payment-result/{applySerialNum} 查询放款申请结果
deactivate Artemis

业务系统 -> Artemis: 4.1.2.1 资金绑卡接口v1（放款卡）
activate Artemis
统一进件 <- Artemis: 快照接口 /api/1.0/loan-app-snapshot
Artemis -> 资金: T2.4.1_设置放款银行卡信息
统一进件 <- Artemis: 更新生效放款卡信息
note right
accountStatus(VALID)、bankAccountInfo.type（PAYEE），从INVALID复制其他字段
end note
deactivate Artemis

业务系统 -> Artemis: 4.1.2.2 协议支付签约申请接口（还款卡）
note right #DarkGrey
协议支付签约调用为optional，仅针对外部资金（如博能小贷）
对于部分资金方，若该还款卡之前做过协议支付签约，则该接口直接返回协议号，不再发送和要求输入验证码
end note
activate Artemis
统一进件 <- Artemis: 快照接口 /api/1.0/loan-app-snapshot
Artemis <-> 资金: T2.5.1_还款卡代扣申请
统一进件 <- Artemis: 更新生效还款卡信息
note right
对部分资金方，如果是之前绑过的卡，或直接返回SUCCESS，这种情况下直接记录还款卡信息生效
accountStatus(VALID)、bankAccountInfo.type（REPAYMENT），从INVALID复制其他字段
协议号： "signId":"8120000000000852838"
end note
deactivate Artemis

业务系统 -> Artemis: 4.1.2.3 协议支付签约确认接口（还款卡）
note right #DarkGrey
协议支付签约调用为optional，仅针对外部资金（如博能小贷）
end note
activate Artemis
统一进件 <- Artemis: 快照接口 /api/1.0/loan-app-snapshot
Artemis <-> 资金: T2.5.2_还款卡代扣确认
统一进件 <- Artemis: 更新生效还款卡信息及agreementSignId
note right
accountStatus(VALID)、bankAccountInfo.type（REPAYMENT），从INVALID复制其他字段
协议号： "signId":"8120000000000852838"
end note
deactivate Artemis

业务系统 -> Artemis: 4.1.7.1 平台扣费服务签约申请
activate Artemis
统一进件 <- Artemis: 快照接口 /api/1.0/loan-app-snapshot
Artemis -> 资金: C1.1.1 签约申请
统一进件 <- Artemis: 更新生效还款卡信息
deactivate Artemis

业务系统 -> Artemis: 4.1.7.2 平台扣费服务签约确认
activate Artemis
统一进件 <- Artemis: 快照接口 /api/1.0/loan-app-snapshot
Artemis -> 资金: C1.1.2 签约确认
统一进件 <- Artemis: 更新生效还款卡信息
deactivate Artemis


@enduml