@startuml
skinparam backgroundColor #FFFFFF
skinparam sequence {
	ArrowColor gray
	ParticipantBorderColor gray
	ParticipantBackgroundColor gray
	ActorBackgroundColor gray
	ActorFontColor #f0f0f0
	LifeLineBorderColor gray
    LifeLineBackgroundColor gray

}

title 找房首页交互时序图
participant 业务APP #FFFFFF
participant 找房api网关 #FFFFFF
participant 找房中台 #FFFFFF
participant UUS #FFFFFF
participant 钱包服务 #FFFFFF



activate 找房api网关 #FFFFFF
业务APP-->找房api网关: 进入钱包首页
找房api网关-->找房中台: 获取token
找房中台-->UUS: 获取token

UUS->找房中台: 返回用户登录的token
找房中台->找房api网关: 返回用户登录的token

找房api网关-->找房中台: 获取首页信息
找房api网关-->钱包服务: 获取首页信息（indexapi接口）
钱包服务-->钱包服务: 拼接首页url以及首页数据
钱包服务->找房中台: 返回首页信息

找房中台->找房api网关: 内部规则判断，过滤首页条目展示

找房api网关->业务APP: 返回首页数据信息


deactivate "找房api网关"




@enduml